name=NotAdafruit SSD1327
version=1.0.0
author=MTK
maintainer=matthew.thomas.kirkwood@gmail.com
sentence=SH1122 library for grayscale OLEDs based on SH1122 drivers
paragraph=SH1122 library for grayscale OLEDs based on SH1122 drivers
category=Display
url=https://github.com/gabsepip/NotAdafruit_SH1122
architectures=*
depends=Adafruit GFX Library
